version: 2
updates:
  # Root pom.xml (parent POM)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Core engine
  - package-ecosystem: "maven"
    directory: "/presto-main"
    schedule:
      interval: "weekly"

  # Presto server module
  - package-ecosystem: "maven"
    directory: "/presto-server"
    schedule:
      interval: "weekly"

  # Presto SPI (common API)
  - package-ecosystem: "maven"
    directory: "/presto-spi"
    schedule:
      interval: "weekly"

  # Testing module
  - package-ecosystem: "maven"
    directory: "/presto-tests"
    schedule:
      interval: "weekly"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker images, if present
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
