openapi: 3.0.0
info:
  title: Presto function signatures API
  description: API for retrieving function signatures in Presto.
  version: "1"
servers:
  - url: http://localhost:8080
    description: Presto endpoint when running locally
paths:
  /v1/functions:
    get:
      summary: Returns the list of function signatures.
      description: This endpoint retrieves the supported function signatures from a Prestissimo cluster.
      responses:
        '200':
          description: List of function signatures.
          content:
            application/json:
              schema:
                $ref: './schemas.yaml/#/components/schemas/JsonBasedUdfFunctionMetadata'
  /v1/functions/{catalog}:
    get:
      summary: Returns the list of function signatures for a specific catalog.
      description: This endpoint retrieves the supported function signatures from a Prestissimo cluster filtered by catalog.
      parameters:
        - name: catalog
          in: path
          required: true
          description: The catalog name to filter functions by
          schema:
            type: string
      responses:
        '200':
          description: List of function signatures for the specified catalog.
          content:
            application/json:
              schema:
                $ref: './schemas.yaml/#/components/schemas/JsonBasedUdfFunctionMetadata'
        '400':
          description: Bad request - Invalid catalog parameter
